### PR TITLE
Version 1.0.0 Polish

### PR DESCRIPTION
**Pull request by ajbarnes**
These updates largely dealt with new styling, new application architecture, package updates, and better documentation. The only change in logic was moving password encryption to be server-side (b4a16c6).

### CODE REVIEW

**Comment by hcientist** [comment]
thanks for all your (continued) hard work on this! have half an hour to meet to review this pull request with me @ajbarnes ?

**Comment by ajbarnes** [comment]
Absolutely. I'll PM you about a time and place.

**Comment by hcientist** [comment]
hey @ajbarnes can you potentially [Enabl[e] repository maintainer permissions on existing pull requests](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests)

**Comment by ajbarnes** [comment]
It seems it was already checked. Feel free?

**Comment by hcientist** [comment]
hmmm, say i deploy this to the server (or test it locally with prod data). the passwords there are all already encrypted via md5. how would this play out...? i think we may need a migration strategy (perhaps we add a md5 column to user and mark existing folks true. then if someone is trying to login, we use the old method, and if it works, we ... store the new encryption and change the flag??)

**Comment by ajbarnes** [comment]
Agreed. Another migration approach could be to null the password columns and prompt for a password reset on the next login. Doing this, we'd avoid any extra columns/ queries but interrupt the UX compared to your approach.

**Comment by hcientist** [comment]
@ajbarnes good point, i think that it wouldn't be too bad since it'd only interrupt them once, but how owuld you know it's them and not someone else accidentally signing in as them? (we would know it's the right person setting the password in the approach i mentioned bc we could check against the current auth info...)

**Comment by ajbarnes** [comment]
I believe the way this problem is typically handled is with a password notification email, but that's not something we currently support. If possible (does prod server support it?), I believe it may be something worthwhile to implement since users will also likely need to reset their passwords when they forget them in addition to situations like these. If not, I believe your approach is best given the current situation.

**Comment by hcientist** [comment]
this is merged.

**Pull request closed without merging**
